# Cloud Build configuration for deploying the V-Ken Serve application to Cloud Run.

steps:
  # Step 1: Build the container image using the Dockerfile.
  # This packages the entire full-stack application.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '.'

  # Step 2: Push the built image to Google Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA'

  # Step 3: Run database migrations using the just-built image.
  # This ensures the database schema is updated before the new service version goes live.
  # It uses the DATABASE_URL secret made available through 'secretEnv'.
  - name: '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA'
    entrypoint: 'npx'
    args: ['prisma', 'migrate', 'deploy']
    secretEnv: ['DATABASE_URL']

  # Step 4: Deploy the new image to Cloud Run.
  # This step makes the service live and connects it to the database and secrets.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Makes the service publicly accessible.
      - '--add-cloudsql-instances'
      - '${_INSTANCE_CONNECTION_NAME}'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest,API_KEY=API_KEY:latest,JWT_SECRET=JWT_SECRET:latest,VAPID_PUBLIC_KEY=VAPID_PUBLIC_KEY:latest,VAPID_PRIVATE_KEY=VAPID_PRIVATE_KEY:latest'

# Store the final image URI in the build details.
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA'

# Default substitution variables. These can be overridden by the trigger settings.
substitutions:
  _SERVICE_NAME: 'vken-serve'
  _REGION: 'asia-south1'
  _REPOSITORY: 'vken-serve-repo'
  _IMAGE_NAME: 'vken-serve-app'
  # IMPORTANT: _INSTANCE_CONNECTION_NAME must be set in your Cloud Build trigger.
  _INSTANCE_CONNECTION_NAME: 'your-gcp-project:your-region:your-instance-name'

# Grant Cloud Build permission to access secrets from Secret Manager during the build.
# Only secrets used by build steps (like migrations) need to be listed here.
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'

# Specify build options.
# This option sends logs directly to Cloud Logging, avoiding Cloud Storage bucket issues.
options:
  logging: CLOUD_LOGGING_ONLY